import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="font-pretendard" suppressHydrationWarning>
      <body className={inter.className}>
        <Toaster
          toastOptions={{
            className: 'font-semibold',
            style: {
              borderRadius: '30px',
              background: '#ffffff',
              color: '#000000',
            },
          }}
          position="bottom-right"
          reverseOrder={false}
        />
        {children}
      </body>
    </html>
  )
}
